// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: bidirectional.proto

package bidirectional

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Bidirectional_GetServerResponse_FullMethodName = "/Bidirectional/GetServerResponse"
)

// BidirectionalClient is the client API for Bidirectional service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BidirectionalClient interface {
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of Message sent while a route is being traversed,
	GetServerResponse(ctx context.Context, opts ...grpc.CallOption) (Bidirectional_GetServerResponseClient, error)
}

type bidirectionalClient struct {
	cc grpc.ClientConnInterface
}

func NewBidirectionalClient(cc grpc.ClientConnInterface) BidirectionalClient {
	return &bidirectionalClient{cc}
}

func (c *bidirectionalClient) GetServerResponse(ctx context.Context, opts ...grpc.CallOption) (Bidirectional_GetServerResponseClient, error) {
	stream, err := c.cc.NewStream(ctx, &Bidirectional_ServiceDesc.Streams[0], Bidirectional_GetServerResponse_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &bidirectionalGetServerResponseClient{stream}
	return x, nil
}

type Bidirectional_GetServerResponseClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type bidirectionalGetServerResponseClient struct {
	grpc.ClientStream
}

func (x *bidirectionalGetServerResponseClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bidirectionalGetServerResponseClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BidirectionalServer is the server API for Bidirectional service.
// All implementations must embed UnimplementedBidirectionalServer
// for forward compatibility
type BidirectionalServer interface {
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of Message sent while a route is being traversed,
	GetServerResponse(Bidirectional_GetServerResponseServer) error
	mustEmbedUnimplementedBidirectionalServer()
}

// UnimplementedBidirectionalServer must be embedded to have forward compatible implementations.
type UnimplementedBidirectionalServer struct {
}

func (UnimplementedBidirectionalServer) GetServerResponse(Bidirectional_GetServerResponseServer) error {
	return status.Errorf(codes.Unimplemented, "method GetServerResponse not implemented")
}
func (UnimplementedBidirectionalServer) mustEmbedUnimplementedBidirectionalServer() {}

// UnsafeBidirectionalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BidirectionalServer will
// result in compilation errors.
type UnsafeBidirectionalServer interface {
	mustEmbedUnimplementedBidirectionalServer()
}

func RegisterBidirectionalServer(s grpc.ServiceRegistrar, srv BidirectionalServer) {
	s.RegisterService(&Bidirectional_ServiceDesc, srv)
}

func _Bidirectional_GetServerResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BidirectionalServer).GetServerResponse(&bidirectionalGetServerResponseServer{stream})
}

type Bidirectional_GetServerResponseServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type bidirectionalGetServerResponseServer struct {
	grpc.ServerStream
}

func (x *bidirectionalGetServerResponseServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bidirectionalGetServerResponseServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Bidirectional_ServiceDesc is the grpc.ServiceDesc for Bidirectional service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bidirectional_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Bidirectional",
	HandlerType: (*BidirectionalServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetServerResponse",
			Handler:       _Bidirectional_GetServerResponse_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bidirectional.proto",
}
